<div class="content">
    <div class="row">
        <p>Selecione a opção lateral para dar inicio a importação dos dados.</p>
        <center>
            <iframe
                sc="https://docs.google.com/forms/d/e/1FAIpQLSe1seqrPoUdUyvstl7zbUaB5ty2j8yKX17d61Oof_gbgiB7RA/viewform?embedded=true"
                width="640" height="2402" frameborder="0" marginheight="0" marginwidth="0">Carregando…</iframe>
        </center>
    </div>
</div>