<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 center">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Olá Seja Bem Vindo.</h4>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="/autenticar">
                            <div class="row">
                                <div class="col-md pr-1">
                                    <div class="form-group">
                                        <label>Empresa</label>
                                        <select name="empresa" id="empresa" class="form-control">
                                            <option value='' id="">Selecione</option>
                                            <?php foreach ($this->view->empresa as $id => $empresa) { ?>
                                                <option value='<?= $empresa['id_empresa'] ?>' id='<?= $empresa['id_empresa'] ?>'><?= $empresa['nome'] ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md pr-1">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Email</label>
                                        <input type="email" class="form-control" placeholder="Email" name="email" id="email">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md pr-1">
                                    <div class="form-group">
                                        <label>Senha</label>
                                        <input type="password" class="form-control" placeholder="Senha" value="" name="senha" id="senha">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md">
                                    <button type="submit" class="btn btn-info btn-fill pull-right">Login</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>