 <div class="container mt-5">
     <div class="col">
         <div class="form-row">
             <div class="form-group col-md">
                 <div class="card">
                     <div class="card-header">
                         <h6><i class="fas fa-archive text-info"></i></i> Estoque.</h6>
                     </div>
                     <div class="card-body">
                         <div class="row">
                             <div class="col-md-4">
                                 <a type="submit" href="/estoque" class="form-control btn btn-primary" id="estoque"><i
                                         class="fas fa-boxes text-dark"></i> <strong>Executar
                                         estoque.</strong></a>
                             </div>
                             <div class="col-md-4">
                                 <a type="submit" href="/artprind" class="form-control btn btn-warning"
                                     id="preco_fornecedor"><i class="fas fa-dollar-sign text-dark"></i><strong> Executar
                                         Preço Fornecedor.</strong></a>
                             </div>
                             <div class="col-md-4">
                                 <a type="submit" href="/artbloqueio" class="form-control btn btn-success"
                                     id="bloqueio_estoque"><i class="fas fa-lock text-dark"></i><strong> Executar
                                         bloqueio estoque.</strong></a>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <div class="col">
         <div class="form-row">
             <div class="form-group col-md">
                 <div class="card">
                     <div class="card-header">
                         <h6><i class="fas fa-store text-info"></i> Pedidos & Financeiro.</h6>
                     </div>
                     <div class="card-body">
                         <div class="row">
                             <div class="col-md-4">
                                 <a type="submit" href="/movped" class="form-control btn btn-primary"
                                     id="movimento_pedido"><i class="fas fa-dolly text-dark"></i><strong> Gera movimento
                                     pedido.</strong></a>
                             </div>
                             <div class="col-md-4">
                                 <a type="submit" href="/movfincab" class="form-control btn btn-warning"
                                     id="movimento_financeiro_cab"><i class="fas fa-piggy-bank"></i><strong> Gera cabeçalho
                                     financeiro.</strong></a>
                             </div>
                             <div class="col-md-4">
                                 <a type="submit" href="/movfincor" class="form-control btn btn-success"
                                     id="movimento_financeiro_cor"><i class="fas fa-donate"></i><strong> Gera corpo
                                     financeiro.</strong></a>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
 </div>