<?php
function logCli($informacao)
{
    $arquivo = './log/'.date('d-m-Y H_m_s').'-log.txt';

    $x = fopen($arquivo, "a+", 0);

    $linha = $informacao . "\n";

    fwrite($x, $linha, strlen($linha));

    fclose($x);
}
?>
<div class="container-fluid mt-5">
    <h6>Data de Hoje: <?=$this->view->dataBD['dia']?></h6>
    <div class="row">
        <div class="col-md-6">
            <div class="form-row">
                <!-- Tabela de informação dos dados que foram importados. -->
                <label for="">População tabelas estoque</label>
                <table class="table table-hover">
                    <thead>
                        <th>Tabela</th>
                        <th>Número Reg.</th>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->tabelas as $id => $info) {?>
                        <tr>
                            <td><?=$info['tab']?></td>
                            <td><?=$info['qtd']?></td>
                        </tr>
                        <?php }?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-row">
                <!-- Tabela de informação dos dados que foram importados. -->
                <label for="">Duplicidade de Registros Clientes</label>
                <table class="table table-hover">
                    <thead>
                        <th>CPF / CNPJ</th>
                        <th>Número Reg.</th>
                    </thead>
                    <tbody>
                        <?php foreach ($this->view->dupCli as $id => $dupCli) { 
                            logCli('CPF/CNPJ : ' . $dupCli['dados'] . ' Duplicados: ' . $dupCli['qtd']);
                        ?>
                        <tr>
                            <td><?=$dupCli['dados']?></td>
                            <td><?=$dupCli['qtd']?></td>
                        </tr>
                        <?php }?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>