 <div class="container mt-5">
     <div class="col">
         <form method="post" action="newDB">
             <div class="form-row">
                 <div class="form-group col-md-6">
                     <label for="usuario">Usuário</label>
                     <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Amadeu">
                 </div>
                 <div class="form-group col-md-6">
                     <label for="nomeBd">Nome do BD</label>
                     <input type="text" class="form-control" id="base" name="base" placeholder="nome_nomebanco_data">
                 </div>
             </div>
             <div class="form-row">
                 <div class="form-group col-md-2">
                     <label for="nomeBd"> </label>
                     <input type="submit" class="form-control btn btn-primary" id="criar" value="Criar">
                 </div>
             </div>
         </form>
     </div>
 </div>